config/routes.rb
Rails.application.routes.draw do
  resources :minesweeper_boards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'minesweeper_boards#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/minesweeper_board.rb
class MinesweeperBoard < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :name, presence: true
  validates :height, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :width, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :mines, presence: true, numericality: { only_integer: true, greater_than: -1 }

  validate :mines_are_less_than_cells, on: :create

  def mines_are_less_than_cells
    return if mines.blank? || width.blank? || height.blank?

    errors.add(:mines, "can't be greater than number of cells") if mines > width * height
  end

  before_save :generate_board

  def generate_board
    self.board_state = BoardGeneratorService.create_board(width, height, mines)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/minesweeper_boards_controller.rb
class MinesweeperBoardsController < ApplicationController
  before_action :set_minesweeper_board, only: %i[show edit update destroy]

  # GET /minesweeper_boards or /minesweeper_boards.json
  def index
    @minesweeper_boards = MinesweeperBoard.all
  end

  # GET /minesweeper_boards/1 or /minesweeper_boards/1.json
  def show; end

  # GET /minesweeper_boards/new
  def new
    @minesweeper_board = MinesweeperBoard.new
    @minesweeper_boards = MinesweeperBoard.all.order(created_at: :desc).limit(10)
  end

  # GET /minesweeper_boards/1/edit
  def edit; end

  # POST /minesweeper_boards or /minesweeper_boards.json
  def create
    @minesweeper_boards = MinesweeperBoard.all.order(created_at: :desc).limit(10)
    @minesweeper_board = MinesweeperBoard.new(minesweeper_board_params)

    respond_to do |format|
      if @minesweeper_board.save
        format.html do
          redirect_to minesweeper_board_url(@minesweeper_board), notice: 'Minesweeper board was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minesweeper_boards/1 or /minesweeper_boards/1.json
  def update
    respond_to do |format|
      if @minesweeper_board.update(minesweeper_board_params)
        format.html do
          redirect_to minesweeper_board_url(@minesweeper_board), notice: 'Minesweeper board was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @minesweeper_board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @minesweeper_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minesweeper_boards/1 or /minesweeper_boards/1.json
  def destroy
    @minesweeper_board.destroy

    respond_to do |format|
      format.html { redirect_to minesweeper_boards_url, notice: 'Minesweeper board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_minesweeper_board
    @minesweeper_board = MinesweeperBoard.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def minesweeper_board_params
    params.fetch(:minesweeper_board).permit(:name, :email, :width, :height, :mines)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MinesweeperGenerator
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css", :integrity => "sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/froala-design-blocks/1.0.2/css/froala_blocks.min.css", :rel => "stylesheet", :type => "text/css"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = yield

app/views/minesweeper_boards/_boards_list.html.haml
%table.table.table-bordered
    %thead
        %tr 
            %th Name 
            %th Email 
            %th Created at
    %tbody 
    - @minesweeper_boards&.each do |minesweeper_board|
        %tr
            %td
                =link_to "#{minesweeper_board.name}", minesweeper_board
            %td
                =minesweeper_board.email
            %td
                =minesweeper_board.created_at

app/views/minesweeper_boards/_form.html.haml
= form_for @minesweeper_board do |f|
  .container
    .row.justify-content-center{ style: "width: 100%" }
      .col-12
        .row.align-items-start
          .col
            = f.text_field :name, class: "form-control", placeholder: "Board Name"
            %div.text-danger.mx-2.text-left{ style: "font-size: 0.8rem" }
              = @minesweeper_board.errors.full_messages_for(:name).uniq[0]
        .row.align-items-start.mt-4
          .col
            = f.text_field :email, type: :email, class: "form-control", placeholder: "Email"
            %div.text-danger.mx-2.text-left{ style: "font-size: 0.8rem" }
              = @minesweeper_board.errors.full_messages_for(:email).uniq[0]
        .row.align-items-start.mt-4
          .col
            = f.number_field :height, class: "form-control", placeholder: "Height"
            %div.text-danger.mx-2.text-left{ style: "font-size: 0.8rem" }
              = @minesweeper_board.errors.full_messages_for(:height).uniq[0]
          .col
            = f.number_field :width, class: "form-control", placeholder: "Width"
            %div.text-danger.mx-2.text-left{ style: "font-size: 0.8rem" }
              = @minesweeper_board.errors.full_messages_for(:width).uniq[0]
          .col
            = f.number_field :mines, class: "form-control", placeholder: "Mines"
            %div.text-danger.mx-2.text-left{ style: "font-size: 0.8rem" }
              = @minesweeper_board.errors.full_messages_for(:mines).uniq[0]
        = f.submit "Generate board", class: "btn btn-primary mt-4 w-100", role: "button"

app/views/minesweeper_boards/_minesweeper_board.haml
-# - debugger
%table.table.table-bordered
    - @minesweeper_board.board_state.each do |row|
        %tr
        - row.each do |cell|
            %td{ style: "height: 50px; width: 50px; text-align: center;" }
                = cell['bomb'] == 1 ? '💣' : "\n" 

app/views/minesweeper_boards/_sidebar.html.haml
%table.table.table-bordered
    %thead
        %tr 
            %th Name 
            %th Email 
            %th Created at
    %tbody 
    - @minesweeper_boards&.each do |minesweeper_board|
        %tr
            %td
                =link_to "#{minesweeper_board.name}", minesweeper_board
            %td
                =minesweeper_board.email
            %td
                =minesweeper_board.created_at

app/views/minesweeper_boards/edit.html.haml
%h1 Editing minesweeper_board

= render 'form'

= link_to 'Show', @minesweeper_board
\|
= link_to 'Back', minesweeper_boards_path

app/views/minesweeper_boards/index.html.haml
%section.fdb-block.text-center.pt-3
  .container
    %h1 Minesweeper boards list
    = render 'boards_list'

app/views/minesweeper_boards/new.html.haml
%section.fdb-block.text-center.pt-5
    %h1{ style: "font-weight: 700; font-size: 56px" } Minesweeper board generator
    %br/
    .fdb-box.fdb-touch.pt-3{ style: "width: 90%; margin: 0 auto; min-height: 70vh" }
        .row
            .col-6
                %h2.text-left
                    Most recently generated boards
                - if @minesweeper_boards.empty?
                    %p.text-left
                        = "No board generated yet"
                - else
                    = render 'boards_list'
                    = link_to 'View all generated boards', minesweeper_boards_path, class: 'btn btn-primary'
            .col-6
                %h2.text-left
                    Generate a new board
                = render 'form'

app/views/minesweeper_boards/show.html.haml
%section.fdb-block.text-center.pt-3{style: "overflow: scroll;"}
    %p#notice= notice
    .container
        .row.ml-2
            = link_to 'Back', root_path, class: 'btn btn-primary'
        %br/
        .row.justify-content-center
        .col-12
            %h1.text-left Details
            .row.justify-content-center
                %table.table.table-bordered
                    %thead
                        %tr 
                            %th Name 
                            %th Email 
                            %th Height 
                            %th Width
                            %th Mines
                            %th Created at
                    %tbody 
                        %tr
                            %td
                                =@minesweeper_board.name
                            %td
                                =@minesweeper_board.email
                            %td
                                =@minesweeper_board.height
                            %td
                                =@minesweeper_board.width
                            %td
                                =@minesweeper_board.mines
                            %td
                                =@minesweeper_board.created_at
        %br/
        .col-12
            %h1.text-left Board
            .row.justify-content-start{ style: "width: #{@minesweeper_board.board_state[0].length * 50}px; overflow: scroll;" }
                = render 'minesweeper_board'